<?php
/**
 * @var $this \Cubex\View\Layout
 */
$am = \Packaged\Dispatch\AssetManager::assetType();
$am->requireCss(
  [
    'css/bootstrap.min',
    'css/business-casual',
  ]
);
$am->requireJs(
  [
    'js/jquery-1.11.0',
    'js/bootstrap.min',
  ]
);
?>
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><?= $this->getData('page.title', 'Demo Corp'); ?></title>

  <?= $am->generateHtmlIncludes('css'); ?>

  <!-- Fonts -->
  <link
    href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    rel="stylesheet" type="text/css">
  <link
    href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic"
    rel="stylesheet" type="text/css">

  <!--[if lt IE 9]>
  <script
    src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script
    src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<div class="brand">Demo Corp</div>
<div class="address-bar">123 Fake Street</div>

<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
      <a class="navbar-brand" href="index.html">Business Casual</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="/">Home</a>
        </li>
        <li>
          <a href="/about">About</a>
        </li>
        <li>
          <a href="/join">Join</a>
        </li>
        <li>
          <a href="/purchase">Purchase</a>
        </li>
        <li>
          <a href="/refund">Refund</a>
        </li>
      </ul>
    </div>
  </div>
  <!-- /.container -->
</nav>

<div class="container">

  <?= $this->content(); ?>

</div>
<!-- /.container -->

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <p>Copyright &copy; Demo Corp 2014</p>
      </div>
    </div>
  </div>
</footer>

<?= $am->generateHtmlIncludes('js'); ?>
<script>
  $('.carousel').carousel(
    {
      interval: 5000 //changes the speed
    }
  )
</script>
<!-- Start of Fortifi Chat config -->
<script>
  window.addEventListener(
    'load', function ()
    {
      fortifiChat.manager.createInstance(
        {
          chatServiceScheme: 'http',
          chatServiceHost:   'chat.fortifi.me',
          chatServicePort:   '8443'
        });
    }
  );
</script>
<!-- End of Fortifi Chat config -->
<!-- Start of Fortifi Chat code -->
<script type="text/javascript">
  (function (d, s, i, u)
  {
    if (d.getElementById(i))
    {return;}
    var n = d.createElement(s), e = d.getElementsByTagName(s)[0];
    n.id = i;
    n.src = '//' + u + '/js/chatManager.js';
    e.parentNode.insertBefore(n, e);
  })(
    document, "script", "fortifi-chat",
    "<?= $this->getData('fortifi.chat.domain'); ?>"
  );
</script>
<!-- End of Fortifi Chat code -->
<!-- Start of Fortifi Code -->
<script type="text/javascript">
  (function (d, s, i, u)
  {
    if (d.getElementById(i))
    {return;}
    var n = d.createElement(s), e = d.getElementsByTagName(s)[0];
    n.id = i;
    n.src = '//' + u + '/fp/init/fortifi.js';
    e.parentNode.insertBefore(n, e);
  })(
    document, "script", "fortifi-track",
    "<?= $this->getData('fortifi.track.domain'); ?>"
  );
</script>
<!-- End of Fortifi Code -->
</body>

</html>
