
<script type="text/javascript">
  var fcConfig = {
    chatService: 'chat.fortifi.xyz'
  };
  (function ()
  {
    var fcLoader = document.createElement('script');
    fcLoader.type = 'text/javascript';
    fcLoader.async = true;
    fcLoader.src = "https://chat.fortifi.xyz/js/chatLoader.js";
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fcLoader, s);
  })();
</script>
