<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">Join Demo Corp</h2>
      <hr>
      <p>Please fill out the form below to join</p>


      <form method="post" action="/join" class="panel form-horizontal">
        <div class="panel-body">
          <div class="form-group">
            <label for="inputEmail2"
                   class="col-sm-2 control-label">Email</label>

            <div class="col-sm-10">
              <input type="text" class="form-control" id="inputEmail2"
                     placeholder="Email">
            </div>
          </div>
          <!-- / .form-group -->
          <div class="form-group">
            <label for="inputPassword"
                   class="col-sm-2 control-label">Password</label>

            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword"
                     placeholder="Password">
            </div>
          </div>
          <!-- / .form-group -->
          <div class="form-group">
            <label for="asdasdas"
                   class="col-sm-2 control-label">Description</label>

            <div class="col-sm-10">
              <textarea class="form-control"></textarea>
            </div>
          </div>
          <!-- / .form-group -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Text</label>

            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios1"
                         value="option1" class="px" checked="">
                  <span class="lbl">Option one is this and that—be sure to include why it's great</span>
                </label>
              </div>
              <!-- / .radio -->
              <div class="radio">
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios2"
                         value="option2" class="px">
                  <span class="lbl">Option two can be something else and selecting it will deselect option one</span>
                </label>
              </div>
              <!-- / .radio -->
              <div class="radio">
                <label>
                  <input type="radio" name="optionsRadios" id="optionsRadios3"
                         value="option3" class="px">
                  <span class="lbl">Option three</span>
                </label>
              </div>
              <!-- / .radio -->
            </div>
            <!-- / .col-sm-10 -->
          </div>
          <!-- / .form-group -->
          <div class="form-group" style="margin-bottom: 0;">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">Join</button>
            </div>
          </div>
          <!-- / .form-group -->
        </div>
      </form>


    </div>
  </div>
</div>

