<div class="row">
  <div class="box">
    <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">Buy A Demo Corp Product</h2>
      <hr>
      <p>Please fill out the form below to purchase</p>

      <form method="post" action="/purchase" class="panel form-horizontal">
        <div class="panel-body">
          <div class="form-group">
            <label for="inputEventRef"
                   class="col-sm-2 control-label">Event Reference</label>

            <div class="col-sm-10">
              <input name="event_ref" type="text" class="form-control"
                     id="inputEventRef"
                     placeholder="e.g. Order ID (Leave Blank For Auto)">
            </div>
          </div>

          <div class="form-group">
            <label for="inputEmail2"
                   class="col-sm-2 control-label">Email</label>

            <div class="col-sm-10">
              <input name="email" type="text" class="form-control"
                     id="inputEmail2"
                     placeholder="Email">
            </div>
          </div>

          <div class="form-group">
            <label for="inputAmount"
                   class="col-sm-2 control-label">Amount</label>

            <div class="col-sm-10">
              <input name="amount" type="text" class="form-control"
                     id="inputAmount"
                     placeholder="0.00">
            </div>
          </div>

          <div class="form-group">
            <label for="asdasdas"
                   class="col-sm-2 control-label">Description</label>

            <div class="col-sm-10">
              <textarea name="description" class="form-control"></textarea>
            </div>
          </div>
          <!-- / .form-group -->
          <div class="form-group">
            <label class="col-sm-2 control-label">Product To Purchase</label>

            <div class="col-sm-10">
              <div class="radio">
                <label>
                  <input type="radio" name="product" id="optionsRadios1"
                         value="product one" class="px" checked="">
                  <span class="lbl">Product One</span>
                </label>
              </div>
              <!-- / .radio -->
              <div class="radio">
                <label>
                  <input type="radio" name="product" id="optionsRadios2"
                         value="product two" class="px">
                  <span class="lbl">Product Two</span>
                </label>
              </div>
              <!-- / .radio -->
              <div class="radio">
                <label>
                  <input type="radio" name="product" id="optionsRadios2-2"
                         value="product three" class="px">
                  <span class="lbl">Product three</span>
                </label>
              </div>
              <!-- / .radio -->
            </div>
            <!-- / .col-sm-10 -->
          </div>

          <div class="form-group">
            <label for="asdasdas"
                   class="col-sm-2 control-label">Coupon</label>

            <div class="col-sm-10">
              <input name="coupon" type="text" class="form-control"
                     id="inputEmail2" placeholder="Coupon">
            </div>
          </div>

          <!-- / .form-group -->
          <div class="form-group" style="margin-bottom: 0;">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">Purchase Product
              </button>
            </div>
          </div>
          <!-- / .form-group -->
        </div>
      </form>

    </div>
  </div>
</div>

